//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerServiceMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerServiceMessage()
        {
            this.BusinessRules_CustomerServiceMessages = new HashSet<BusinessRules_CustomerServiceMessages>();
            this.CustomerServiceMessage_Sections = new HashSet<CustomerServiceMessage_Sections>();
            this.Defect_CustomerServiceMessages = new HashSet<Defect_CustomerServiceMessages>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public long fk_StatusID { get; set; }
        public long fk_CSMTypeID { get; set; }
        public long fk_CSMResponseTypeID { get; set; }
        public string Text { get; set; }
        public long fk_SectionID { get; set; }
        public bool Active { get; set; }
        public long UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessRules_CustomerServiceMessages> BusinessRules_CustomerServiceMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerServiceMessage_Sections> CustomerServiceMessage_Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defect_CustomerServiceMessages> Defect_CustomerServiceMessages { get; set; }
    }
}
