//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigation_Menu_Items
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string NodeID { get; set; }
        public Nullable<long> FeatureID { get; set; }
    }
}
