//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PalinoiaEntities : DbContext
    {
        public PalinoiaEntities()
            : base("name=PalinoiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessRule_Sections> BusinessRule_Sections { get; set; }
        public virtual DbSet<BusinessRule> BusinessRules { get; set; }
        public virtual DbSet<BusinessRules_CustomerServiceMessages> BusinessRules_CustomerServiceMessages { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }
        public virtual DbSet<CustomerServiceMessage_Sections> CustomerServiceMessage_Sections { get; set; }
        public virtual DbSet<CustomerServiceMessage> CustomerServiceMessages { get; set; }
        public virtual DbSet<Defect_BusinessRules> Defect_BusinessRules { get; set; }
        public virtual DbSet<Defect_Comments> Defect_Comments { get; set; }
        public virtual DbSet<Defect_CustomerServiceMessages> Defect_CustomerServiceMessages { get; set; }
        public virtual DbSet<Defect_TestCases> Defect_TestCases { get; set; }
        public virtual DbSet<Defect> Defects { get; set; }
        public virtual DbSet<Document_Chapters> Document_Chapters { get; set; }
        public virtual DbSet<DocumentImage> DocumentImages { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<lkup_ChapterType> lkup_ChapterType { get; set; }
        public virtual DbSet<lkup_CSMResponseType> lkup_CSMResponseType { get; set; }
        public virtual DbSet<lkup_CSMType> lkup_CSMType { get; set; }
        public virtual DbSet<lkup_DefectPriority> lkup_DefectPriority { get; set; }
        public virtual DbSet<lkup_DefectStatus> lkup_DefectStatus { get; set; }
        public virtual DbSet<lkup_DefectType> lkup_DefectType { get; set; }
        public virtual DbSet<lkup_DocumentType> lkup_DocumentType { get; set; }
        public virtual DbSet<lkup_PalinoiaFields> lkup_PalinoiaFields { get; set; }
        public virtual DbSet<lkup_PalinoiaObjects> lkup_PalinoiaObjects { get; set; }
        public virtual DbSet<lkup_SearchDataTypes> lkup_SearchDataTypes { get; set; }
        public virtual DbSet<lkup_SearchObjects> lkup_SearchObjects { get; set; }
        public virtual DbSet<lkup_SearchOperators> lkup_SearchOperators { get; set; }
        public virtual DbSet<lkup_SearchTypes> lkup_SearchTypes { get; set; }
        public virtual DbSet<lkup_Sections> lkup_Sections { get; set; }
        public virtual DbSet<lkup_Status> lkup_Status { get; set; }
        public virtual DbSet<lkup_TestStatus> lkup_TestStatus { get; set; }
        public virtual DbSet<SQLITEADMIN_QUERIES> SQLITEADMIN_QUERIES { get; set; }
        public virtual DbSet<TestCase_BusinessRules> TestCase_BusinessRules { get; set; }
        public virtual DbSet<TestCase_Documents> TestCase_Documents { get; set; }
        public virtual DbSet<TestCase_PreConditions> TestCase_PreConditions { get; set; }
        public virtual DbSet<TestCase_TestSteps> TestCase_TestSteps { get; set; }
        public virtual DbSet<TestCas> TestCases { get; set; }
        public virtual DbSet<TestResult> TestResults { get; set; }
        public virtual DbSet<TestStep_BusinessRules> TestStep_BusinessRules { get; set; }
        public virtual DbSet<TestStep> TestSteps { get; set; }
    }
}
