//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestCas()
        {
            this.Defect_TestCases = new HashSet<Defect_TestCases>();
            this.TestCase_BusinessRules = new HashSet<TestCase_BusinessRules>();
            this.TestCase_Documents = new HashSet<TestCase_Documents>();
            this.TestCase_PreConditions = new HashSet<TestCase_PreConditions>();
        }
    
        public long ID { get; set; }
        public Nullable<long> fk_lkup_SectionID { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public bool Active { get; set; }
        public long UpdatedBy { get; set; }
        public long fk_TestStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defect_TestCases> Defect_TestCases { get; set; }
        public virtual lkup_TestStatus lkup_TestStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestCase_BusinessRules> TestCase_BusinessRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestCase_Documents> TestCase_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestCase_PreConditions> TestCase_PreConditions { get; set; }
    }
}
