//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCase_Documents
    {
        public long ID { get; set; }
        public long fk_TestCaseID { get; set; }
        public long fk_DocumentID { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual TestCas TestCas { get; set; }
    }
}
