//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class applicationEntities1 : DbContext
    {
        public applicationEntities1()
            : base("name=applicationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application_Errors> Application_Errors { get; set; }
        public virtual DbSet<Application_History> Application_History { get; set; }
        public virtual DbSet<lkup_ApplicationFields> lkup_ApplicationFields { get; set; }
        public virtual DbSet<lkup_ApplicationObjects> lkup_ApplicationObjects { get; set; }
        public virtual DbSet<lkup_Features> lkup_Features { get; set; }
        public virtual DbSet<lkup_Roles> lkup_Roles { get; set; }
        public virtual DbSet<Navigation_Menu_Items> Navigation_Menu_Items { get; set; }
        public virtual DbSet<Palinoia_Projects> Palinoia_Projects { get; set; }
        public virtual DbSet<Role_Features> Role_Features { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
