//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Defect()
        {
            this.Defect_BusinessRules = new HashSet<Defect_BusinessRules>();
            this.Defect_Comments = new HashSet<Defect_Comments>();
            this.Defect_CustomerServiceMessages = new HashSet<Defect_CustomerServiceMessages>();
            this.Defect_TestCases = new HashSet<Defect_TestCases>();
        }
    
        public long ID { get; set; }
        public long fk_DefectPriorityID { get; set; }
        public long fk_DefectStatusID { get; set; }
        public long fk_DefectTypeID { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public string DefectName { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public bool Closed { get; set; }
        public long UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defect_BusinessRules> Defect_BusinessRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defect_Comments> Defect_Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defect_CustomerServiceMessages> Defect_CustomerServiceMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defect_TestCases> Defect_TestCases { get; set; }
    }
}
