//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkup_CSMType
    {
        public long ID { get; set; }
        public string Text { get; set; }
        public bool Active { get; set; }
        public long UpdatedBy { get; set; }
    }
}
